PREFIX csa: <https://omilab.org/experiments/city-swift-aid#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?sensor ?sensorType WHERE {
  {person} csa:hasSensor ?sensor .
  ?sensor a ?sensorType .
}