PREFIX csa: <https://omilab.org/experiments/city-swift-aid#>

SELECT ?person ?name ?ssn ?location
WHERE {
  ?person a csa:Person ;
          csa:hasName ?name ;
          csa:hasSSN ?ssn ;
          csa:locatedAt ?location .

  FILTER(?ssn = "{SSN}")
}