PREFIX csa: <https://omilab.org/experiments/city-swift-aid#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
  ?emergency_id a csa:Emergency ;
      csa:associatedWithSSN "{patient_ssn}"^^xsd:string ;
      csa:requiresTreatmentLevel [
          a csa:TreatmentLevel ;
          csa:requiresCertificationLevel csa:{level} ;
          csa:requiresSpecialty csa:{speciality} ;
          csa:hasMeasurementValuePair [
              a csa:MeasurementValuePair ;
              csa:hasMeasurement csa:{measurement} ;
              csa:hasValue csa:{value}
          ]
      ] ;
      csa:hasStatus [
          a csa:ReportedStatus ;
          csa:statusTimestamp ?current_time
      ] .
}
WHERE {
  BIND(UUID() AS ?emergency_id)
  BIND(NOW() AS ?current_time)
}