PREFIX csa: <https://omilab.org/experiments/city-swift-aid#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

    INSERT DATA {
        csa:{id} a csa:FirstResponder ;
            csa:hasSSN "{ssn}"^^xsd:string ;
            csa:hasName "{name}"^^xsd:string ;
            csa:locatedAt csa:{target_location} ;
            csa:holdsCertification [
                a csa:Certification ;
                csa:hasCertificationLevel csa:{certificationLevel} ;
                csa:certificationSpecialty csa:{speciality}
            ] .

    }