PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX csa: <https://omilab.org/experiments/city-swift-aid#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?person ?street ?ssn WHERE {
    ?person csa:locatedAt ?street .
    ?person csa:hasSSN ?ssn .
    ?person csa:holdsCertification [
        a csa:Certification ;
        csa:hasCertificationLevel ?level ;
        csa:certificationSpecialty csa:{speciality}
    ] .
    ?level rdfs:subClassOf csa:{level} .
    FILTER NOT EXISTS {
        ?person csa:hasSSN "{ssn}"^^xsd:string
    }
    FILTER NOT EXISTS {
        ?person csa:hasDeclined "true" .
    }

}