PREFIX csa: <https://omilab.org/experiments/city-swift-aid#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
    ?person csa:hasHealthMeasurement [
        a csa:MeasurementValuePair ;
        csa:hasMeasurement csa:{measurement_type} ;
        csa:hasValue csa:{category}
    ] .
}
WHERE {
    ?person csa:hasSSN "{ssn}" .
}