PREFIX csa: <https://omilab.org/experiments/city-swift-aid#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
    csa:{ssn} csa:hasHealthMeasurement [
        a csa:MeasurementValuePair ;
        csa:hasMeasurementType {illness_type} ;
        csa:hasMeasurementValue {category}
    ] .
}