PREFIX csa: <https://omilab.org/experiments/city-swift-aid#>
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

    INSERT DATA {
        {person_uri} a csa:FirstResponder ;
            csa:hasSSN "{ssn}"^^xsd:string ;
            csa:hasName "{name}"^^xsd:string ;
            csa:locatedAt csa:{located_at} .
    }