PREFIX csa: <https://omilab.org/experiments/city-swift-aid#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?person ?personName ?totalDistance
WHERE {

{patient}
 csa:locatedAt ?targetLocation .

    ?person a csa:Person ;
            csa:hasName ?personName ;
            csa:locatedAt ?personLocation .
    FILTER(?person != {patient})

    ?targetLocation csa:connectedTo* ?personLocation .

    # total distance
    {
        SELECT ?personLocation (SUM(?segmentLength) AS ?totalDistance)
        WHERE {
            ?targetLocation csa:connectedTo* ?midSegment .
            ?midSegment csa:connectedTo* ?personLocation .
            ?midSegment csa:hasLengthMeters ?segmentLength .
        }
        GROUP BY ?personLocation
    }
}
ORDER BY ASC(?totalDistance)
LIMIT 5